# Generated by Django 2.2.2 on 2019-06-08 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='employees.Employee'),
            preserve_default=False,
        ),
    ]
