# Generated by Django 2.2.2 on 2019-06-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20190608_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='', upload_to='files'),
            preserve_default=False,
        ),
    ]
