# Generated by Django 2.2.2 on 2019-06-08 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20190608_1842'),
        ('overtime_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerecords',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
    ]
