# Generated by Django 2.2.2 on 2019-06-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime_records', '0003_auto_20190608_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerecords',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
